# -*- coding: utf-8 -*-
"""Renewable_Energy_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yI4K4FGhYnaGSAdYSrSIbZ5rI5-UjaHA

## **Title-26: Renewable Energy Usage Analysis**

### **Objective:**  
Analyze the adoption of renewable energy sources across regions.

### **Dataset:**  
`renewable_energy.csv`  
Columns:  
`region, year, solar_kwh, wind_kwh, hydro_kwh, total_consumption`
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### **Load Dataset**"""

try:
    df = pd.read_csv('renewable_energy.csv')
    print("File loaded successfully.")
    display(df.head())
except FileNotFoundError:
    print("Error: 'renewable_energy.csv' not found. Please upload the file to your Colab environment.")
except Exception as e:
    print(f"An error occurred: {e}")

"""### **Handle Missing Renewable Values (Forward Fill)**"""

df[['solar_kwh', 'wind_kwh', 'hydro_kwh']] = df[['solar_kwh', 'wind_kwh', 'hydro_kwh']].ffill()

print("Missing values in solar_kwh, wind_kwh, and hydro_kwh handled using forward fill.")

"""## **Q1: Calculate total renewable contribution by region. [CO1, BL3]**"""

df['total_renewable'] = df['solar_kwh'] + df['wind_kwh'] + df['hydro_kwh']
region_contribution = df.groupby('region')['total_renewable'].sum().reset_index()
print(region_contribution)

"""## **Q2: Compare solar vs wind usage across years. [CO2, BL4]**"""

solar_wind = df.groupby('year')[['solar_kwh', 'wind_kwh']].sum().reset_index()
plt.figure(figsize=(8,5))
plt.plot(solar_wind['year'], solar_wind['solar_kwh'], marker='o', label='Solar')
plt.plot(solar_wind['year'], solar_wind['wind_kwh'], marker='s', label='Wind')
plt.xlabel('Year')
plt.ylabel('Energy (kWh)')
plt.title('Solar vs Wind Usage Across Years')
plt.legend()
plt.show()

"""## **Q3: Impute missing hydro_kwh with mean. [CO3, BL3]**"""

df.fillna({'hydro_kwh': df['hydro_kwh'].mean()}, inplace=True)

print('Missing values handled successfully.')

"""## **Q4: Analyze correlation between renewable usage and total_consumption. [CO4, BL4]**"""

corr = df[['solar_kwh', 'wind_kwh', 'hydro_kwh', 'total_consumption']].corr()
sns.heatmap(corr, annot=True, cmap='Greens')
plt.title('Correlation Matrix')
plt.show()

"""## **Q5: Create stacked bar plots and trend lines. [CO5, BL5]**"""

region_year = df.groupby(['region', 'year'])[['solar_kwh', 'wind_kwh', 'hydro_kwh']].sum().reset_index()
region_year.set_index(['region', 'year'], inplace=True)
region_year.plot(kind='bar', stacked=True, figsize=(10,6))
plt.title('Stacked Renewable Energy Contribution by Region and Year')
plt.ylabel('Energy (kWh)')
plt.show()

# Trend line for total renewable
plt.figure(figsize=(8,5))
sns.lineplot(x='year', y='total_renewable', data=df, estimator='sum', ci=None)
plt.title('Trend of Total Renewable Energy Over Years')
plt.xlabel('Year')
plt.ylabel('Total Renewable (kWh)')
plt.show()